
-- ==========================================
-- Ejercicio 1 para la casa
-- ==========================================

/*
Desarrollar un procedimiento que descompomga 
una cantidad de dinero:
- Si el dato es 1268
- El resultado debe ser:
- Billetes de 200: 
- Billetes de 100:
- Billetes de 50: 
- Billetes de 20:
- Billetes de 10:
- Monedas de 5:
- Billetes de 1:
*/

-- ==========================================
-- Ejercicio 2 para la casa
-- ==========================================
/*
- Hacer dos funciones, una parea encontrar el MCD de dos
- números y otra para encontrar el MCM de dos números
*/



